.PHONY: install
install:
    python3 -m venv venv &&
    pip install -r requirements.txt &&
    source venv/bin/activate &&
    python manage.py runserver &&
    echo "Все работает, даун."

.DEFAULT_GOAL := install
