.PHONY: install
install:
    cd django_hack_app_life
    pip install -r requirements.txt &&
    source venv/bin/activate &&
    python manage.py runserver &&
    echo "Все работает, даун."

.DEFAULT_GOAL := install